(part "S101031MS02Q"
    (packageRef "S101031MS02Q")
    (interface
        (port "1" (symbPinId 1) (portName "NC") (portType INOUT))
        (port "2" (symbPinId 2) (portName "COM") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "LITTELFUSE")
    (property "Manufacturer_Part_Number" "S101031MS02Q")
    (property "Mouser_Part_Number" "611-S101031MS02Q")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/CK/S101031MS02Q?qs=rSrlmGad8O4HSGnv%2FMP6JQ%3D%3D")
    (property "Arrow_Part_Number" "S101031MS02Q")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/s101031ms02q/ck?utm_currency=USD&region=nac")
    (property "Description" "Slide Switches SPST 6A PC TH AG")
    (property "Datasheet_Link" "https://www.ckswitches.com/media/1433/s.pdf")
    (property "symbolName1" "S101031MS02Q")
)
